config/routes.rb
Foodhosting::Application.routes.draw do

  devise_for :users

  root :to => 'static#home'
  
  get "about" => "static#about"

  get "findhost" => "static#findhost"
  
  

  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end

  def about
  end

  def findhost
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Foodhosting</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
<link href='http://fonts.googleapis.com/css?family=Open+Sans|Merriweather|Expletus+Sans|Arvo' rel='stylesheet' type='text/css'>
<style type="text/css">
</style>
</head>
<body>
	<div class="navbar navbar-fixed-top">
	      <div class="navbar-inner" style="height: 80px;">
	        <div class="container" style="padding-top: 30px;">
			<!--<a class="logo" href="./index.html" style="padding-top: 20px;">food hosting</a>-->
			<%= link_to "food hosting", root_path, id: "logo" %>
			
				<ul class="nav pull-right">
				<li class=""><%= link_to "About Us", about_path %></li>
				<li class=""><%= link_to "How It Works", '#' %></li>
				<li class=""><%= link_to "Find Host", findhost_path %></li>
				<%= link_to "Sign up as local!", new_user_registration_path, class: "btn btn-large btn-primary" %>
				</ul>
			
	        </div>
	      </div>
	</div>
    <div>
        <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
        <% end %>
        <%= yield %>
    </div>
	<footer>
		<div class="container">
			<h1></h1>
	<!-- DC Facebook Likes Start -->
		<iframe src="http://www.facebook.com/plugins/like.php?href=http://www.meatbonetea.com&send=false&layout=standard&width=250&show_faces=false&action=like&colorscheme=light&font&height=35" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:250px; height:35px;" allowTransparency="true"></iframe>
	<!-- DC Facebook Likes End -->
		</div>
	</footer>
</body>
</html>